### ISSUE TITLE
A question about SeqCNV.R

### ISSUE THREAD

**Issue by Karma0alpha** [NKI-GCF/SeqCNV#1]
Excuse me, Sir. I saw the SeqCNV.R contains some functions, but I don't know how to take it to analysis sequence data and what the resullt format ?

**Comment by veldsla** [comment]
Hi. Right, this was originally put online to share with a collaborator. It is functionally OK, but requires additional data. Most importantly the the mappability data (which is derived by aligning the reference sequence to itself).

Also in the meantime more complete solutions than this became available, e.g [QDNAseq](http://bioconductor.org/packages/release/bioc/html/QDNAseq.html) uses a similar approach and provides the complete pipeline to go from aligned reads to copy number profiles. Would this also suit your needs?

**Comment by Karma0alpha** [comment]
Ok, Sir.Thank you very much for your prompt reply.
Good luck and best wishes!
