### ISSUE TITLE
separate_chrom.pl throws errors

### ISSUE THREAD

**Issue by geekgeekhello** [NKI-GCF/SeqCNV#2]
I am trying to use SeqCNV to call CNVs on a disease sample and a non-matched control sample. 

Seems the very first script that run_CNV.pl calls is throwing some errors:
perl -I  separate_chrom.pl -f <target.bed> -c <control.bam> -t <disease.bam> -o <output_dir>

It keeps throwing messages like below: 
Number found where operator expected at <target.bed> line 1, near "67021549	67021551"

The <target.bed> is a 3-col bed file like below:
chr1[tab delimited]67021549[tab delimited]67021551

Would you please suggest how I should proceed? I can provide the input files to you if needed.

**Comment by veldsla** [comment]
This repo doesn't contain the program you are referring to. A quick search gives me this http://www.iipl.fudan.edu.cn/SeqCNV/ which probably is what you are using. There's an email address for questions.
